Add new nav links and dynamic base address service
Mikkelkorsaa/famm pull request #67
Opened 2024-12-10 12:47 UTC by asgermunk

Add new nav links and dynamic base address service

- Added "Upload Abstract" and "Min Profil" links to NavMenu.razor.
- Modified Program.cs to add a scoped service for dynamic base address configuration based on the environment.

2024-12-10 12:49 UTC, Mikkelrv requested changes

2024-12-10 12:49 UTC, Mikkelrv commented on conferencePlanner/conferencePlannerApp/Layout/NavMenu.razor
> +                </li>
Indsend Abstrakt > Upload Abstract

2024-12-10 19:05 UTC, Mikkelkorsaa requested changes
fix warnings

2024-12-11 08:03 UTC, Mikkelrv approved these changes

2024-12-11 08:07 UTC, Mikkelkorsaa approved these changes

2024-12-11 08:13 UTC, merged